// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wztkwwqacqpfwrlslfis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dGt3d3FhY3FwZndybHNsZmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjM3NDYsImV4cCI6MjA2NTE5OTc0Nn0.Tm1z_7s99IexAur5mONZ4oEnbiG8ZhaV4EnX5SxQQvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);